# Generated by Django 3.2.25 on 2024-04-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('name', models.CharField(default='', max_length=100)),
                ('force', models.CharField(default='', max_length=50)),
                ('level', models.CharField(default='', max_length=50)),
                ('mechanic', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('equipment', models.CharField(default='', max_length=100)),
                ('primary_muscles', models.TextField(default='[]')),
                ('secondary_muscles', models.TextField(default='[]')),
                ('instructions', models.TextField(default='[]')),
                ('category', models.CharField(default='', max_length=50)),
                ('images', models.TextField(default='[]')),
                ('id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
