# Generated by Django 5.0.4 on 2024-04-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('name', models.CharField(default='', max_length=100000)),
                ('force', models.CharField(default='', max_length=100000)),
                ('level', models.CharField(default='', max_length=100000)),
                ('mechanic', models.CharField(default='', max_length=100000)),
                ('equipment', models.CharField(default='', max_length=100000)),
                ('primaryMuscles', models.CharField(default='', max_length=100000)),
                ('secondaryMuscles', models.CharField(default='', max_length=100000)),
                ('instructions', models.CharField(default='', max_length=100000)),
                ('category', models.CharField(default='', max_length=100000)),
                ('images', models.CharField(default='', max_length=100000)),
                ('id', models.CharField(default='', max_length=100000, primary_key=True, serialize=False)),
            ],
        ),
    ]
