# Generated by Django 3.2.25 on 2024-04-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240423_0802'),
    ]

    operations = [
    ]
