# Generated by Django 3.2.25 on 2024-04-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240423_0804'),
    ]

    operations = [
    ]
