# Generated by Django 3.2.25 on 2024-04-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20240423_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='category',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='force',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='images',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='level',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='mechanic',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='primary_muscles',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='secondary_muscles',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
