# Generated by Django 3.2.25 on 2024-04-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240423_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='force',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='exercise',
            name='level',
            field=models.CharField(default='', max_length=50),
        ),
    ]
