# Generated by Django 3.2.25 on 2024-04-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20240423_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='exercise',
            name='mechanic',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='primary_muscles',
            field=models.TextField(default='[]'),
        ),
    ]
