# Generated by Django 3.2.25 on 2024-04-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20240423_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='exercise',
            name='images',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.TextField(default='[]'),
        ),
    ]
