# Generated by Django 3.2.25 on 2024-04-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20240423_0820'),
    ]

    operations = [
    ]
