# Generated by Django 3.2.25 on 2024-04-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20240423_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='primary_muscles',
            new_name='primaryMuscles',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='secondary_muscles',
            new_name='secondaryMuscles',
        ),
    ]
