# Generated by Django 3.2.25 on 2024-04-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20240423_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='force',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.CharField(default='', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='images',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='level',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='mechanic',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='primaryMuscles',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='secondaryMuscles',
            field=models.CharField(default='', max_length=500),
        ),
    ]
